---
title: "Data Exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(DBI)
library(ggplot2)
```

```{r}
# Connect to Database
con <- RSQLite::dbConnect(RSQLite::SQLite(), "db.sqlite")
```



```{r}

results <- dbGetQuery(con, "
  SELECT * 
  FROM results
") %>% 
  tibble()

```


```{r}

results %>% 
  filter(party %in% c("SPD", "FDP"), rep == 1, seq == 1) %>% 
  group_by(party, step, statement_id) %>% 
  summarize(party_mean_position = mean(position)) %>% 
  ungroup() %>% 
  pivot_wider(id_cols = c(step, statement_id), names_from = party, values_from = party_mean_position) %>% 
  mutate(difference = abs(SPD - FDP)) %>% 
  select(step, statement_id, difference) %>% 
  ggplot(aes(x = step, y = statement_id, group = statement_id, color = difference)) +
  geom_line(size = 2) +
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme(
    panel.background = element_rect(fill = "black"),
    panel.grid = element_blank()
  ) +
  NULL
  
```


```{r}

results %>% 
  filter(rep == 1) %>% 
  group_by(party, step, rep, statement_id, seq) %>% 
  summarize(party_position = mean(position)) %>% 
  ungroup() %>% 
  ggplot(aes(x = step, y = party, color = party_position)) +
  geom_line(size = 3) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red") +
  scale_x_continuous(breaks = seq(0, 6)) +
  facet_grid(rows = vars(statement_id)) +
  theme(
    text = element_text(family = "Courier", color = "white"),
    legend.position = "None",
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    panel.grid = element_blank(),
    axis.text = element_text(color = "grey80"),
    strip.background = element_rect(fill = "grey20"),
    strip.text = element_text(color = "white")
  ) +
  NULL

ggsave(filename = "test.png", width = 8, height = 22)

```



```{r}

results %>% 
  filter(statement_id <= 10, seq == 1, rep == 1) %>% 
  ggplot(aes(x = step, y = position, color = party, group = agent_id)) +
  geom_line(alpha = 0.1) +
  geom_point() +
  facet_grid(rows = vars(statement_id))




```







```{r}
# Disconnect from Database
RSQLite::dbDisconnect(conn = con)

```

