---
title: "Similarity Evolution"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(DBI)
library(ggplot2)
```


```{r}
# Connect to Database
con <- RSQLite::dbConnect(RSQLite::SQLite(), "db.sqlite")
```


```{r}

results <- dbGetQuery(con, "
  SELECT * 
  FROM results
") %>% 
  tibble()

```


```{r}
results %>% 
  filter(rep == 1) %>% 
  group_by(party, step, rep, statement_id, seq) %>% 
  summarize(party_position = mean(position)) %>% 
  ungroup() %>% 
  ggplot(aes(x = step, y = party, color = party_position)) +
  geom_line(size = 3) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red") +
  scale_x_continuous(breaks = seq(0, 6)) +
  facet_grid(rows = vars(statement_id)) +
  theme(
    text = element_text(family = "Courier", color = "white"),
    legend.position = "None",
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    panel.grid = element_blank(),
    axis.text = element_text(color = "grey80"),
    strip.background = element_rect(fill = "grey20"),
    strip.text = element_text(color = "white")
  ) +
  NULL

ggsave(filename = file.path("plots", "similarity_evolution.png"), width = 8, height = 22)

```